import { createClient } from '@supabase/supabase-js';

// Import from Figma Make Supabase Integration (autogenerated file)
import { projectId, publicAnonKey } from './info.tsx';

// Fail-fast validation: ensure Supabase credentials are available
if (!projectId || !publicAnonKey) {
  const errorMsg = 'FATAL: Missing Supabase credentials. Please check Figma Make Supabase Integration.';
  console.error(errorMsg, { projectId: !!projectId, publicAnonKey: !!publicAnonKey });
  throw new Error(errorMsg);
}

// Validate project ID format (should be gxethvdtqpqtfibpznub)
if (projectId !== 'gxethvdtqpqtfibpznub') {
  console.warn('⚠️ Unexpected Supabase project ID:', projectId);
  console.warn('Expected: gxethvdtqpqtfibpznub');
}

// Construct Supabase URL from project ID (never hardcoded)
const supabaseUrl = `https://${projectId}.supabase.co`;
const supabaseAnonKey = publicAnonKey;

// Create single Supabase client instance with auth configuration
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'trimly-auth-token',
  }
});

// Export config for debugging
export const supabaseConfig = {
  url: supabaseUrl,
  projectId,
  isCorrectProject: projectId === 'gxethvdtqpqtfibpznub'
};

// Debug logging (dev/preview only)
if (typeof window !== 'undefined') {
  const isDev = window.location.hostname === 'localhost' || 
                window.location.hostname.includes('figma') ||
                window.location.hostname.includes('preview');
  
  if (isDev) {
    console.log('🔌 [Supabase Client] Connected:', {
      url: `${supabaseUrl.slice(0, 15)}...${supabaseUrl.slice(-15)}`,
      projectId: projectId,
      isCorrectProject: projectId === 'gxethvdtqpqtfibpznub',
      keyPrefix: supabaseAnonKey.slice(0, 15) + '...',
      authConfig: 'persistSession: true, autoRefreshToken: true'
    });
  }
}